#!/bin/env bash


source bashlib_y


G_USER=`git config user.name`
if [ -z "$G_USER" ];the
	die "Missing user for git. Please set user by executing 'git user.name USER_NAME/git user.email EMAIL'"
fi

if ! [[ $1 =~ ^[0-9A-Za-z_]+$ ]];then
	die "Illeagal name, '$1'"
fi

mkdir -p ~/git_project/$1
cd ~/git_project/$1

if ! [ -d ~/git_project/$1/.git ];then
	echo "# $1" >> README.md
	git init
	git add README.md
	git commit -m "0"
	git branch -M main
	git remote add origin git@github.com:$G_USER/$1.git
	git push -u origin main
else
	git remote add origin git@github.com:$G_USER/$1.git
	git branch -M main
	git push -u origin main
fi


